services:
  - type: web
    name: visitor-management
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && ./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DJANGO_SETTINGS_MODULE
        value: visitor_management.settings
      - key: DATABASE_URL
        fromDatabase:
          name: visitor-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
    plan: free
    numInstances: 1

  - type: postgres
    name: visitor-management-db
    plan: free
    databaseName: visitor_management
    user: admin
    ipAllowList:
      - 0.0.0.0/0
