services:
  - type: web
    name: visitor-management-backend
    env: python
    buildCommand: |
      cd backend && 
      pip install -r requirements.txt && 
      python manage.py migrate
    startCommand: "cd backend && gunicorn visitor_management.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DJANGO_SETTINGS_MODULE
        value: visitor_management.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
    plan: free
