services:
  - type: web
    name: visitor-management-backend
    env: python
    buildCommand: |
      cd /opt/render/project/src/backend &&
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src/backend &&
      python manage.py migrate &&
      gunicorn visitor_management.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DJANGO_SETTINGS_MODULE
        value: visitor_management.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    plan: free

databases:
  - name: visitor-management-db
    databaseName: visitor_management
    user: postgres
    plan: free
