# Generated by Django 5.2.4 on 2025-08-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visit_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='host_name',
        ),
    ]
