# Generated by Django 4.2.7 on 2025-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_host_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='host_name',
            field=models.CharField(blank=True, help_text='Name of the person being visited', max_length=200),
        ),
    ]
