# Generated by Django 4.2.7 on 2025-08-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_customadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded signature data', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_signatures/'),
        ),
    ]
