services:
  - type: web
    name: visitor-management
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python wait_for_railway.py && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn visitor_management.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DJANGO_SETTINGS_MODULE
        value: visitor_management.settings
      - key: DATABASE_URL
        value: postgresql://postgres:uEutQJRqyRbgOlzwhsGGgczYXaeBqgxI@yamabiko.proxy.rlwy.net:14599/railway
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
    plan: free
    numInstances: 1

