services:
  - type: web
    name: visitor-management
    env: python
    buildCommand: pip install -r visitors-managment/backend/requirements.txt
    startCommand: cd visitors-managment/backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn visitor_management.wsgi:application --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: DJANGO_SETTINGS_MODULE
        value: visitor_management.settings
      - key: DATABASE_URL
        fromDatabase:
          name: visitor-management-db
          property: connectionString
      - key: RENDER
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
    plan: free
    numInstances: 1

databases:
  - name: visitor-management-db
    databaseName: visitor_management
    user: visitor_user
    plan: free
